# Generated by Django 3.0.5 on 2020-04-30 07:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200429_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 7, 3, 56, 182113, tzinfo=utc)),
        ),
    ]
