# Generated by Django 3.0.5 on 2020-04-30 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200430_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 7, 57, 24, 223254, tzinfo=utc)),
        ),
    ]
